#!/usr/bin/env bash

set -euo pipefail

APP_NAME="IntelliJ IDEA Ultimate"

if [ "$#" -ge 1 ]; then
  open -a "${APP_NAME}" "$@"
  exit 0
fi

projectFile=$(find . -maxdepth 1 -name '*.ipr')

if test -z $projectFile
then
  echo Project file not found!
  open -a "${APP_NAME}" .
  exit 0
fi

open -a "${APP_NAME}" $projectFile
