#!/usr/bin/env bash
set -euo pipefail

if ! colima status 2>/dev/null ; then
    echo "Starting colima..."
    colima start
fi

docker run --rm -u "$(id -u):$(id -g)" -v "$PWD:/data" minlag/mermaid-cli "$@"
