#!/bin/bash

set -e

source .profile

mkdir -p ${owasp_cache_dir}

dependency-check \
	-d ${owasp_cache_dir} \
	-f ALL \
	--purge \
	| true

dependency-check \
	-d ${owasp_cache_dir} \
	-f ALL \
	--updateonly \
	$@
