#!/bin/bash

set -e

source $(dirname "$0")/.profile

mkdir -p ${owasp_cache_dir}/log

/usr/local/bin/dependency-check \
	-d ${owasp_cache_dir} \
	-f ALL \
	--cveValidForHours 1 \
	--updateonly \
	$@
