#!/bin/bash

set -e

source .profile

actual_vpn=${default_vpn_domain}

disconnect() {
  killall 'Cisco AnyConnect Secure Mobility Client' 2>/dev/null || true
  /opt/cisco/anyconnect/bin/vpn disconnect >/dev/null
}

usage() {
  echo "Usage: vpn [-h] [-x] [-d domain] [-s vpn_server]" 1>&2
  echo "Options:" 1>&2
  echo "  [without any option]" 1>&2
  echo "          Connect default vpn specified in .profile and domain script." 1>&2
  echo "  -h" 1>&2
  echo "          Show script usage" 1>&2
  echo "  -x" 1>&2
  echo "          Disconnect & quit VPN" 1>&2
  echo "  -d a_domain" 1>&2
  echo "          Connect to 'a_domain' with its default/selected vpn server" 1>&2
  echo "  -s a_server" 1>&2
  echo "          Connect to 'a_server' in default/selected domain" 1>&2
}

while getopts ":hxd:s:" opt; do
  case ${opt} in
    h )
      usage
      exit 0
      ;;
    d )
      actual_vpn=${OPTARG}
      if [ -z "${actual_vpn}" ]; then
        usage
        exit 1
      fi
      ;;
    s )
      vpn_server=${OPTARG}
      if [ -z "${vpn_server}" ]; then
        usage
        exit 1
      fi
      ;;
    x )
      echo '  >> Disconnecting ......'
      disconnect
      exit 0
      ;;
    * )
      usage
      exit 1
      ;;
  esac
done

echo "  >> Using domain: ${actual_vpn}"

${script_folder}/vpn_${actual_vpn} ${vpn_server}

open -g "$vpn_app"
