#!/bin/bash

set -e

if [ $# -eq 0 ]
  then
    echo "No arguments supplied. Use personal url"
fi

if [ -z "$2" ]
  then
    echo "No domain provided, infered ThoughtWorks."
fi

meeting_id=${1:-yaodan}
domain=${2:-thoughtworks}

echo $meeting_id
echo $domain

number_regex='^[0-9]+$'
if [[ $meeting_id =~ $number_regex ]] ; then
  url="https://${domain}.zoom.us/j/${meeting_id}"
else
  url="https://${domain}.zoom.us/my/${meeting_id}"	
fi

echo $url | pbcopy

open $url

